spring:
  application:
    name: easy-ai-agent
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.85
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
server:
  servlet:
    context-path: /ai-agent
  port: 8080
knife4j:
  basic:
    enable: true